name: arkmoon-survival
version: git
summary: ARKMOON
description: >
  Think you have the ingenuity to be an astronaut? Let's find out.

confinement: devmode

parts:
  arkmoon-survival:
    plugin: python
    python-version: python2
    source: .

apps:
    securelock:
        command: main.py  
